backend:
  name: git-gateway
  branch: master
site_url: https://insitu-gardens.netlify.com/
publish_mode: editorial_workflow
media_folder: "src/dist/images" # Media files will be stored in the repo under images/uploads
public_folder: "dist/images"
collections:
  - name: "pages"
    label: "Pages"
    description: "All non-unique site pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - label: "Banner"
        name: "banner"
        widget: "object"
        required: false
        fields: 
          - {label: "Image", name: "src", widget: "image", media_library: { config: { multiple: false }}, required: false}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "gallery-pages"
    label: "Gallery Pages"
    description: "Pages that use the gallery template"
    folder: "src/galleries"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "gallery"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - label: "Banner"
        name: "banner"
        widget: "object"
        required: false
        fields: 
          - {label: "Image", name: "src", widget: "image", media_library: { config: { multiple: false }}, required: false}
      - label: "Gallery Images"
        label_singular: "Image"
        name: "gallery"
        widget: "list" 
        required: false
        fields: 
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Image", name: "src", widget: "image", media_library: { config: { multiple: false }} }
          - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
                    
  - name: "unique-pages"
    label: "Unique Pages"
    description: "One-off pages with unique fields for each page."
    files: 
      - file: "src/index.md"
        label: "Home Page"
        name: "home-page"
        create: false
        fields: 
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "string", default: "page"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - label: "Gallery Images"
            label_singular: "Image"
            name: "gallery"
            widget: "list" 
            required: false
            fields: 
              - {label: "Image", name: "src", widget: "image", media_library: { config: { multiple: false }}}
              - {label: "Body", name: "body", widget: "markdown"}
                          
  - name: "Settings"
    label: "Settings"
    description: "Configure the settings for the site."
    files: 
      - file: "src/_data/settings.json"
        label: "Global Settings"
        name: "global-settings"
        create: false
        fields: 
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Tagline", name: "tagline", widget: "string"}
          - {label: "Default Page Banner", name: "default_banner", widget: "image", media_library: { config: { multiple: false } } }
          - label: "Navigation Links"
            name: "nav_links"
            widget: "list" 
            required: false
            fields: 
              - label: "Nav Link"
                name: "nav_link"
                widget: "object"
                required: false
                fields: 
                  - {label: "Label", name: "label", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
                                  